version: '3'
services:
  registry:
    image: registry:2
    restart: always
    container_name: registry
    volumes:
      - registrydata:/data
      - ./auth:/auth
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry-Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/registry.passwd
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
      REGISTRY_HTTP_MAXCONCURRENTUPLOADS: 5
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.whoami.entrypoints=websecure
        - traefik.http.routers.whoami.rule=Host(`api.registry.viomitra.ru`)
        - traefik.http.routers.whoami.tls=true
        # min TLS version
        - traefik.http.routers.whoami.tls.certresolver=le
        - traefik.http.routers.whoami.middlewares=traefik-ratelimit
        - traefik.http.services.whoami.loadbalancer.server.port=5000
    networks:
      - registry
      - traefik-public
  registry-ui:
    image: joxit/docker-registry-ui:latest
    restart: always
    container_name: registry-ui
    environment:
      - REGISTRY_TITLE=Private Docker Registry
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SINGLE_REGISTRY=true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.registry_ui-http.rule=Host(`ui.registry.viomitra.ru`)
        - traefik.http.routers.registry_ui-http.entrypoints=http
        - traefik.http.routers.registry_ui-http.middlewares=https-redirect
        - traefik.http.routers.registry_ui-https.rule=Host(`ui.registry.viomitra.ru`)
        - traefik.http.routers.registry_ui-https.entrypoints=https
        - traefik.http.routers.registry_ui-https.tls=true
        - traefik.http.routers.registry_ui-https.tls.certresolver=le
        - traefik.http.services.registry_ui.loadbalancer.server.port=80
    depends_on:
      - registry
    networks:
      - registry
      - traefik-public

volumes:
  registrydata:
    driver: local
networks:
  registry:
  traefik-public:
    external: true