version: '3'
services:
  registry:
    image: registry:2
    restart: always
    container_name: registry
    volumes:
      - registrydata:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
          - "traefik.enable=true" 
          - "traefik.http.routers.registry-secure.entrypoints=https"
          - "traefik.http.routers.registry-secure.rule=Host(`api.registry.viomitra.ru`) && Method(`GET`, `HEAD`, `POST`, `PUT`, `DELETE`, `PATCH`)"
          - "traefik.http.routers.registry-secure.tls=true"
          - "traefik.http.routers.registry-secure.service=registry"
          - "traefik.http.middlewares.registry-auth.basicauth.users=reguser:$$2y$$05$$dkGwIwecWdYE2mDXPNHzlO.M7AGLMjr2MsSjJTylxWdK35JivqyHS"
          - "traefik.http.routers.registry-secure.middlewares=registry-auth"
          - "traefik.http.services.registry.loadbalancer.server.port=5000"
          - "traefik.http.routers.guest-registry-secure.entrypoints=https"
          - "traefik.http.routers.guest-registry-secure.rule=Host(`api.registry.viomitra.ru`) && Method(`GET`, `HEAD`)"
          - "traefik.http.routers.guest-registry-secure.tls=true"
          - "traefik.http.routers.guest-registry-secure.service=guest-registry"
          - "traefik.http.routers.guest-registry-secure.middlewares=guest-registry-auth"
          - "traefik.http.services.guest-registry.loadbalancer.server.port=5000"
    networks:
      - registry
      - traefik-public
  registry-ui:
    image: joxit/docker-registry-ui:latest
    restart: always
    container_name: registry-ui
    environment:
      - REGISTRY_TITLE=Private Docker Registry
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - SINGLE_REGISTRY=true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.portainer-http.rule=Host(`ui.registry.viomitra.ru`)
        - traefik.http.routers.portainer-http.entrypoints=http
        - traefik.http.routers.portainer-http.middlewares=https-redirect
        - traefik.http.routers.portainer-https.rule=Host(`ui.registry.viomitra.ru`)
        - traefik.http.routers.portainer-https.entrypoints=https
        - traefik.http.routers.portainer-https.tls=true
        - traefik.http.routers.portainer-https.tls.certresolver=le
        - traefik.http.services.portainer.loadbalancer.server.port=80
    depends_on:
      - registry
    networks:
      - registry
      - traefik-public

volumes:
  registrydata:
    driver: local
networks:
  registry:
  traefik-public:
    external: true