version: '3.7'

services:
  postgresql-server:
    image: postgres:latest
    container_name: postgresql-server
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=false

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    restart: unless-stopped
    depends_on:
      - postgresql-server
    environment:
      DB_SERVER_HOST: postgresql-server
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "10051:10051"
    volumes:
      - zabbix-server-data:/var/lib/zabbix
      - zabbix-snmptraps-data:/var/lib/zabbix/snmptraps
      - zabbix-export-data:/var/lib/zabbix/export
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=false

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web
    restart: unless-stopped
    depends_on:
      - postgresql-server
      - zabbix-server
    environment:
      DB_SERVER_HOST: postgresql-server
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: ${PHP_TZ}
    volumes:
      - zabbix-web-data:/usr/share/zabbix
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.zabbix-http.rule=Host(`zabbix.viomitra.ru`)
        - traefik.http.routers.zabbix-http.entrypoints=http
        - traefik.http.routers.zabbix-http.middlewares=https-redirect
        - traefik.http.routers.zabbix-https.rule=Host(`zabbix.viomitra.ru`)
        - traefik.http.routers.zabbix-https.entrypoints=https
        - traefik.http.routers.zabbix-https.tls=true
        - traefik.http.routers.zabbix-https.tls.certresolver=le
        - traefik.http.services.zabbix.loadbalancer.server.port=8080

  # zabbix-agent:
  #   image: zabbix/zabbix-agent:latest
  #   container_name: zabbix-agent
  #   restart: unless-stopped
  #   depends_on:
  #     - zabbix-server
  #   environment:
  #     ZBX_HOSTNAME: "Zabbix server"
  #     ZBX_SERVER_HOST: zabbix-server
  #     ZBX_SERVER_PORT: '10051'
  #     ZBX_SERVER_ACTIVE: zabbix-server
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #     placement:
  #       constraints: [node.role == manager]
  #     labels:
  #       - traefik.enable=false
  #   ports:
  #     - "10050:10050"

volumes:
  postgresql-data:
  zabbix-server-data:
  zabbix-snmptraps-data:
  zabbix-export-data:
  zabbix-web-data: