version: "3.7"

services:
  fluentd:
    image: api.registry.viomitra.ru/fluentd:latest
    volumes:
      - ./fluentd/conf/fluent.conf:/fluentd/etc/fluent.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 3g
      labels:
        - "traefik.enable=false"

  elasticsearch:
    image: elasticsearch:8.14.1
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - http.host=0.0.0.0
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - network.host=0.0.0.0
      - xpack.security.transport.ssl.enabled=false
    volumes:
      - esdata:/usr/sharehttps://dev.realty.viomitra.ru//elasticsearch/data
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 3g
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.elasticsearch-http.rule=Host(`elastic.viomitra.ru`)"
        - "traefik.http.routers.elasticsearch-http.entrypoints=http"
        - "traefik.http.routers.elasticsearch-http.middlewares=https-redirect"
        - "traefik.http.routers.elasticsearch-https.rule=Host(`elastic.viomitra.ru`)"
        - "traefik.http.routers.elasticsearch-https.entrypoints=https"
        - "traefik.http.routers.elasticsearch-https.tls=true"
        - "traefik.http.routers.elasticsearch-https.tls.certresolver=le"
        - "traefik.http.services.elasticsearch.loadbalancer.server.port=9200"

  kibana:
    image: kibana:8.14.1
    depends_on:
      - elasticsearch
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - traefik-public
    ports: # Runs kibana service on default port 5601
      - 5601:5601
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          memory: 3g
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-public"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.kibana-http.rule=Host(`kibana.viomitra.ru`)"
        - "traefik.http.routers.kibana-http.entrypoints=http"
        - "traefik.http.routers.kibana-http.middlewares=https-redirect"
        - "traefik.http.routers.kibana-https.rule=Host(`kibana.viomitra.ru`)"
        - "traefik.http.routers.kibana-https.entrypoints=https"
        - "traefik.http.routers.kibana-https.tls=true"
        - "traefik.http.routers.kibana-https.tls.certresolver=le"
        - "traefik.http.services.kibana.loadbalancer.server.port=5601"

networks:
  traefik-public:
    external: true

volumes:
  esdata:
    driver: local
